name: flutter_zaptap
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_markdown: ^0.7.1
  sqflite: ^2.3.0
  uuid: ^4.4.0
  keyboard_actions: ^4.2.0
  image_picker: ^1.1.1
  path_provider: ^2.0.11
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  image_gallery_saver: ^1.7.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: M_PLUS_Rounded_1c
      fonts:
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Thin.ttf
          weight: 100
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Light.ttf
          weight: 300
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Regular.ttf
          weight: 400
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Medium.ttf
          weight: 500
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Bold.ttf
          weight: 700
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/M_PLUS_Rounded_1c/MPLUSRounded1c-Black.ttf
          weight: 900

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/ZapTapIcon_1024x1024.png"